import type { Metadata } from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {Toaster} from "@/components/ui/sonner";
import {dbConnect} from "@/services/mongo";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Learning Platform courses",
    description: "Generated by create next app",
};

const poppins = Inter({
    subsets: ['latin'],
    variable: '--font-poppins'
})

export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>) {

    const dbConnection = await dbConnect();

    return (
        <html lang="en">
            <body
                className={cn(`${geistSans.variable} ${geistMono.variable} antialiased, ${poppins.className}`)}
            >
                {children}
                <Toaster richColors={true} position="top-center"/>
            </body>
        </html>
    );
}
